const {
  SLACK_API_TOKEN,
  TELEGRAM_BOT_TOKEN,

  MOBIUS_API_AUTH,
  MOBIUS_API_HOST,
  MOBIUS_API_KEY,
  MOBIUS_TOKEN_UID,

  DEFAULT_TIP_AMOUNT,
  MAX_TIP,
  MAX_TIP_LIFETIME,

  MONGODB_URI,
  MONGODB_URL,
} = process.env;

module.exports = {
  SLACK_API_TOKEN,
  TELEGRAM_BOT_TOKEN,

  MOBIUS_API_AUTH,
  MOBIUS_API_HOST,
  MOBIUS_API_KEY,
  MOBIUS_TOKEN_UID,

  DEFAULT_TIP_AMOUNT: parseInt(DEFAULT_TIP_AMOUNT, 10),
  MAX_TIP: parseInt(MAX_TIP, 10),
  MAX_TIP_LIFETIME: parseInt(MAX_TIP_LIFETIME, 10),

  MONGODB_URL: MONGODB_URL || MONGODB_URI,
};
