const {
  SLACK_API_TOKEN,
  MOBIUS_API_HOST,
  MOBIUS_API_KEY,
  MOBIUS_TOKEN_UID,
  DEFAULT_TIP_AMOUNT,
  REDIS_URL,
  REDISTOGO_URL,
} = process.env;

module.exports = {
  SLACK_API_TOKEN,
  MOBIUS_API_HOST,
  MOBIUS_API_KEY,
  MOBIUS_TOKEN_UID,
  DEFAULT_TIP_AMOUNT,

  REDIS_URL: REDIS_URL || REDISTOGO_URL,
};
